## Importando Bibliotecas

In [2]:
import numpy as np

## Criando um np.array()

np.array(): É um tipo especial de array que suporta operações de vetores/matrizes

In [2]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


np.copy(): Copia um numpy array

In [3]:
x = np.array([1, 2, 3])
print(x)
y = np.copy(x)
print(y)

[1 2 3]
[1 2 3]


np.empty(): Cria um numpy array vazio com shape definida

In [4]:
x = np.empty(shape=(3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Operações

np.sum(): Soma os elementos de um numpy array em um determinado eixo

In [4]:
x = np.array([1, 2, 3])
print(np.sum(x))

6


In [8]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print(np.sum(x, axis=0))

[5 7 9]


In [9]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print(np.sum(x, axis=1))

[ 6 15]


"+": Soma elemento a elemento

In [10]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(x + 1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
y = np.copy(x)
print(x + y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


"-": Subtração elemento a elemento

In [12]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(x - 1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
y = np.copy(x)
print(x - y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


"*": Multiplicação elemento a elemento

In [14]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
y = np.copy(x)
print(x * y)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


"/": Divisão elemento a elemento (// para divisão inteira)

In [16]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(x / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [17]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
y = np.copy(x)
print(x / y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


"@" ou np.matmul(): Multiplicação de matriz

In [23]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
y = np.array([1, 2, 3])
print(x @ y)
print(np.matmul(x, y)) # Since x is an 3x3 matrix and y an 3x1, the multiplication is possible and the result is an 3x1

[14 32 50]
[14 32 50]
