In [1]:
import numpy as np

np.array(): It's an special type of array that supports vector/matrix operations

In [2]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


np.copy(): Copies an numpy array

In [3]:
x = np.array([1, 2, 3])
print(x)
y = np.copy(x)
print(y)

[1 2 3]
[1 2 3]


np.empty(): Creates an empty numpy array with a defined shape

In [4]:
x = np.empty(shape=(3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
